#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# GAF WiFi Management System — Full Zero-Config Deployment
# Fresh Ubuntu 20.04/22.04/24.04 | Node 20 | nginx | PM2
#
# Usage:  sudo bash deploy.sh
# Re-run: sudo bash deploy.sh   (safe to run multiple times)
# ─────────────────────────────────────────────────────────────────────────────

set -e

# ── Config ────────────────────────────────────────────────────────────────────
APP_DIR="/var/www/airforce-wifi-app"
REPO="https://github.com/BRIGHTEDUFUL/airforce-wifi-app.git"
NGINX_CONF="/etc/nginx/sites-available/gaf-wifi"
NETPLAN_CONF="/etc/netplan/99-gaf-static.yaml"
STATIC_IP="192.168.11.10"
GATEWAY="192.168.11.1"
NODE_VERSION="20"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
log()  { echo -e "${GREEN}[✓] $1${NC}"; }
warn() { echo -e "${YELLOW}[!] $1${NC}"; }
fail() { echo -e "${RED}[✗] $1${NC}"; exit 1; }

# ── Must run as root ──────────────────────────────────────────────────────────
[ "$(id -u)" -eq 0 ] || fail "Run with: sudo bash deploy.sh"

# Detect real user — handle both: sudo bash deploy.sh  AND  bash deploy.sh as root
if [ -n "${SUDO_USER:-}" ] && [ "${SUDO_USER}" != "root" ]; then
  REAL_USER="$SUDO_USER"
else
  # Running directly as root — use root's home
  REAL_USER="root"
fi
REAL_HOME=$(getent passwd "$REAL_USER" | cut -d: -f6)

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   GAF WiFi Management System — Deployment"
echo "   User: $REAL_USER | Home: $REAL_HOME | IP: $STATIC_IP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ── 1. System packages ────────────────────────────────────────────────────────
log "Updating system packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
  build-essential python3 python3-pip curl git net-tools ufw ca-certificates gnupg

# ── 2. Node.js 20 ─────────────────────────────────────────────────────────────
if ! command -v node &>/dev/null || [[ "$(node -v 2>/dev/null)" != v${NODE_VERSION}* ]]; then
  log "Installing Node.js ${NODE_VERSION}..."
  # Remove any old nodejs first
  apt-get remove -y nodejs npm 2>/dev/null || true
  # Use NodeSource setup script
  curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x -o /tmp/nodesource_setup.sh
  bash /tmp/nodesource_setup.sh
  apt-get install -y -qq nodejs
  rm -f /tmp/nodesource_setup.sh
  log "Node.js $(node -v) + npm $(npm -v) installed"
else
  log "Node.js $(node -v) already installed"
fi

# ── 3. nginx ──────────────────────────────────────────────────────────────────
if ! command -v nginx &>/dev/null; then
  log "Installing nginx..."
  apt-get install -y -qq nginx
fi
log "nginx ready"

# ── 4. PM2 ────────────────────────────────────────────────────────────────────
if ! command -v pm2 &>/dev/null; then
  log "Installing PM2 globally..."
  npm install -g pm2
fi
log "PM2 $(pm2 -v) ready"

# ── 5. Static IP via netplan ──────────────────────────────────────────────────
log "Configuring static IP ${STATIC_IP}..."

# Detect primary ethernet interface (skip loopback, docker, virtual)
IFACE=$(ip -o link show | awk -F': ' \
  '$2 !~ /^lo$/ && $2 !~ /^docker/ && $2 !~ /^br-/ && $2 !~ /^veth/ && $2 !~ /^virbr/ \
  { gsub(/@.*/, "", $2); print $2; exit }')

if [ -z "$IFACE" ]; then
  warn "Could not detect network interface — skipping static IP (configure manually)"
else
  CURRENT_IP=$(ip -4 addr show "$IFACE" 2>/dev/null | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1 || true)

  if [ "$CURRENT_IP" = "$STATIC_IP" ]; then
    log "Static IP ${STATIC_IP} already set on $IFACE"
  else
    warn "Interface $IFACE has IP: ${CURRENT_IP:-none} — setting to ${STATIC_IP}"

    # Backup existing netplan configs that mention this interface
    for f in /etc/netplan/*.yaml /etc/netplan/*.yml; do
      if [ -f "$f" ] && [ "$f" != "$NETPLAN_CONF" ]; then
        if grep -q "$IFACE" "$f" 2>/dev/null; then
          cp "$f" "${f}.bak.$(date +%s)"
          warn "Backed up existing netplan: $f"
        fi
      fi
    done

    # Write our static IP config
    cat > "$NETPLAN_CONF" << NETEOF
# GAF WiFi Server — Static IP (auto-generated by deploy.sh)
network:
  version: 2
  renderer: networkd
  ethernets:
    ${IFACE}:
      dhcp4: false
      addresses:
        - ${STATIC_IP}/24
      routes:
        - to: default
          via: ${GATEWAY}
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
NETEOF
    chmod 600 "$NETPLAN_CONF"

    # Apply — use || true so SSH drop doesn't abort the script
    netplan generate 2>/dev/null || true
    netplan apply 2>/dev/null || true
    sleep 5

    NEW_IP=$(ip -4 addr show "$IFACE" 2>/dev/null | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1 || true)
    if [ "$NEW_IP" = "$STATIC_IP" ]; then
      log "Static IP confirmed: ${STATIC_IP} on $IFACE"
    else
      warn "IP is now: ${NEW_IP:-unknown}. If SSH dropped, reconnect to ${STATIC_IP} and re-run."
    fi
  fi
fi

# ── 6. App directory ──────────────────────────────────────────────────────────
mkdir -p /var/www
if [ -d "$APP_DIR/.git" ]; then
  log "Pulling latest code..."
  git -C "$APP_DIR" fetch origin main
  git -C "$APP_DIR" reset --hard origin/main
else
  log "Cloning repository..."
  git clone "$REPO" "$APP_DIR"
fi

chown -R "$REAL_USER:$REAL_USER" "$APP_DIR"
cd "$APP_DIR"

# ── 7. Directories ────────────────────────────────────────────────────────────
mkdir -p "$APP_DIR/data" "$APP_DIR/logs"
chown -R "$REAL_USER:$REAL_USER" "$APP_DIR/data" "$APP_DIR/logs"
chmod 750 "$APP_DIR/data"
log "Directories ready"

# ── 8. .env file ──────────────────────────────────────────────────────────────
if [ ! -f "$APP_DIR/.env" ]; then
  log "Creating .env..."
  cat > "$APP_DIR/.env" << ENVEOF
PORT=3000
BASE_URL=http://${STATIC_IP}
JWT_SECRET=
JWT_EXPIRY=8h
GEMINI_API_KEY=
ENVEOF
  chmod 600 "$APP_DIR/.env"
  chown "$REAL_USER:$REAL_USER" "$APP_DIR/.env"
  log ".env created"
else
  log ".env already exists — keeping it"
fi

# ── 9. npm install (clean Linux build) ───────────────────────────────────────
log "Installing npm dependencies (clean build for Linux)..."
# Clear npm cache owned by root to avoid permission conflicts
npm cache clean --force 2>/dev/null || true

if [ "$REAL_USER" = "root" ]; then
  cd "$APP_DIR"
  rm -rf node_modules
  npm install --no-audit --no-fund
else
  # Run as the real user so npm cache is owned correctly
  sudo -u "$REAL_USER" bash << NPMEOF
    cd "$APP_DIR"
    rm -rf node_modules
    npm install --no-audit --no-fund
NPMEOF
fi
log "Dependencies installed"

# ── 10. Build frontend ────────────────────────────────────────────────────────
log "Building frontend..."
if [ "$REAL_USER" = "root" ]; then
  cd "$APP_DIR" && npm run build
else
  sudo -u "$REAL_USER" bash << BUILDEOF
    cd "$APP_DIR"
    npm run build
BUILDEOF
fi
[ -d "$APP_DIR/dist" ] || fail "Build failed — dist/ directory not created"
log "Frontend built successfully"

# ── 11. nginx config ──────────────────────────────────────────────────────────
log "Configuring nginx..."
cp "$APP_DIR/nginx/gaf-wifi.conf" "$NGINX_CONF"
ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/gaf-wifi
rm -f /etc/nginx/sites-enabled/default
nginx -t || fail "nginx config test failed — check $NGINX_CONF"
systemctl enable nginx
systemctl restart nginx
log "nginx running on port 80"

# ── 12. Firewall ──────────────────────────────────────────────────────────────
log "Configuring firewall..."
# Add SSH rule BEFORE resetting to avoid lockout
ufw allow 22/tcp   2>/dev/null || true
ufw allow 80/tcp   2>/dev/null || true
ufw deny  3000/tcp 2>/dev/null || true
ufw default deny incoming  2>/dev/null || true
ufw default allow outgoing 2>/dev/null || true
ufw --force enable 2>/dev/null || true
log "Firewall: SSH(22) + HTTP(80) open | Node(3000) blocked externally"

# ── 13. PM2 — start app ───────────────────────────────────────────────────────
log "Starting app with PM2..."

# Stop existing instance if running
if [ "$REAL_USER" = "root" ]; then
  pm2 stop airforce-app   2>/dev/null || true
  pm2 delete airforce-app 2>/dev/null || true
  pm2 flush               2>/dev/null || true
  cd "$APP_DIR"
  pm2 start ecosystem.config.cjs --env production
  pm2 save --force
else
  sudo -u "$REAL_USER" bash << PM2EOF
    pm2 stop airforce-app   2>/dev/null || true
    pm2 delete airforce-app 2>/dev/null || true
    pm2 flush               2>/dev/null || true
    cd "$APP_DIR"
    pm2 start ecosystem.config.cjs --env production
    pm2 save --force
PM2EOF
fi

# ── 14. PM2 startup on boot ───────────────────────────────────────────────────
log "Configuring PM2 auto-start on reboot..."
# Generate the startup command and execute it
STARTUP_CMD=$(sudo -u "$REAL_USER" pm2 startup systemd -u "$REAL_USER" --hp "$REAL_HOME" 2>/dev/null | grep "sudo env PATH" || true)
if [ -n "$STARTUP_CMD" ]; then
  eval "$STARTUP_CMD" || true
else
  # Fallback: run as root directly
  pm2 startup systemd -u "$REAL_USER" --hp "$REAL_HOME" 2>/dev/null || true
fi
systemctl enable "pm2-${REAL_USER}" 2>/dev/null || true
log "PM2 will auto-start on reboot"

# ── 15. PM2 log rotation ──────────────────────────────────────────────────────
if [ "$REAL_USER" = "root" ]; then
  pm2 install pm2-logrotate 2>/dev/null || true
  pm2 set pm2-logrotate:max_size 10M  2>/dev/null || true
  pm2 set pm2-logrotate:retain 7      2>/dev/null || true
  pm2 set pm2-logrotate:compress true 2>/dev/null || true
else
  sudo -u "$REAL_USER" bash << LOGEOF
    pm2 install pm2-logrotate 2>/dev/null || true
    pm2 set pm2-logrotate:max_size 10M  2>/dev/null || true
    pm2 set pm2-logrotate:retain 7      2>/dev/null || true
    pm2 set pm2-logrotate:compress true 2>/dev/null || true
LOGEOF
fi
log "Log rotation configured"

# ── 16. Health check ──────────────────────────────────────────────────────────
log "Waiting for server to start..."
HTTP="000"
for i in $(seq 1 20); do
  sleep 3
  HTTP=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:3000/api/health 2>/dev/null || echo "000")
  if [ "$HTTP" = "200" ]; then break; fi
  echo "   Waiting... ($i/20) — got HTTP $HTTP"
done

if [ "$HTTP" != "200" ]; then
  warn "Server not responding after 60s. PM2 logs:"
  echo ""
  if [ "$REAL_USER" = "root" ]; then
    pm2 logs airforce-app --lines 50 --nostream 2>/dev/null || true
  else
    sudo -u "$REAL_USER" pm2 logs airforce-app --lines 50 --nostream 2>/dev/null || true
  fi
  echo ""
  fail "Server failed to start. Fix errors above and re-run: sudo bash deploy.sh"
fi
log "Node server healthy (HTTP 200)"

# Verify nginx is proxying correctly
NGINX_HTTP=$(curl -s -o /dev/null -w "%{http_code}" "http://${STATIC_IP}/api/health" 2>/dev/null || echo "000")
if [ "$NGINX_HTTP" = "200" ]; then
  log "nginx proxy healthy (HTTP 200 via http://${STATIC_IP})"
else
  warn "nginx proxy check: HTTP $NGINX_HTTP — run: sudo nginx -t && sudo systemctl status nginx"
fi

# ── 17. Seed admin account ────────────────────────────────────────────────────
log "Seeding admin account..."
if [ "$REAL_USER" = "root" ]; then
  cd "$APP_DIR" && NODE_ENV=production ./node_modules/.bin/tsx scripts/reset-admin.ts
else
  sudo -u "$REAL_USER" bash << ADMINEOF
    cd "$APP_DIR"
    NODE_ENV=production ./node_modules/.bin/tsx scripts/reset-admin.ts
ADMINEOF
fi
log "Admin account ready"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}   Deployment complete!${NC}"
echo ""
echo "   App URL  : http://${STATIC_IP}"
echo "   Login    : admin@airforce.mil"
echo "   Password : Admin@GAF2026!"
echo ""
echo "   Any device on 192.168.11.x → open http://${STATIC_IP}"
echo ""
echo "   pm2 status                — check app"
echo "   pm2 logs airforce-app     — live logs"
echo "   pm2 restart airforce-app  — restart"
echo "   sudo bash update.sh       — pull & redeploy"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
