#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# GAF WiFi Management System — Zero-Config Deployment
# Ubuntu 20.04+ | Node 20 | nginx | PM2
#
# Usage:  sudo bash deploy.sh
# Re-run: sudo bash deploy.sh   (safe to run multiple times)
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
APP_DIR="/var/www/airforce-wifi-app"
REPO="https://github.com/BRIGHTEDUFUL/airforce-wifi-app.git"
NGINX_CONF="/etc/nginx/sites-available/gaf-wifi"
NETPLAN_CONF="/etc/netplan/99-gaf-static.yaml"
STATIC_IP="192.168.11.10"
GATEWAY="192.168.11.1"
NODE_VERSION="20"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
log()  { echo -e "${GREEN}[✓] $1${NC}"; }
warn() { echo -e "${YELLOW}[!] $1${NC}"; }
fail() { echo -e "${RED}[✗] $1${NC}"; exit 1; }

# Must run as root
[ "$(id -u)" -eq 0 ] || fail "Run with: sudo bash deploy.sh"

# Detect the real user (the one who ran sudo)
REAL_USER="${SUDO_USER:-$USER}"
REAL_HOME=$(getent passwd "$REAL_USER" | cut -d: -f6)

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   GAF WiFi Management System — Deployment"
echo "   User: $REAL_USER  |  IP: $STATIC_IP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ── 1. System packages ────────────────────────────────────────────────────────
log "Updating system packages..."
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y \
  build-essential python3 curl git net-tools ufw -qq

# Node.js 20
if ! command -v node &>/dev/null || [[ "$(node -v)" != v${NODE_VERSION}* ]]; then
  log "Installing Node.js ${NODE_VERSION}..."
  curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - >/dev/null 2>&1
  DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs -qq
  log "Node.js $(node -v) installed"
else
  log "Node.js $(node -v) already installed"
fi

# nginx
if ! command -v nginx &>/dev/null; then
  log "Installing nginx..."
  DEBIAN_FRONTEND=noninteractive apt-get install -y nginx -qq
fi
log "nginx ready"

# PM2 (install globally as root so systemd service works)
if ! command -v pm2 &>/dev/null; then
  log "Installing PM2..."
  npm install -g pm2 --quiet --no-progress
fi
log "PM2 $(pm2 -v) ready"

# ── 2. Static IP via netplan ──────────────────────────────────────────────────
log "Configuring static IP ${STATIC_IP}..."

IFACE=$(ip -o link show | awk -F': ' '
  $2 !~ /^lo$/ && $2 !~ /^docker/ && $2 !~ /^br-/ && $2 !~ /^veth/ && $2 !~ /^virbr/
  { print $2; exit }
')

if [ -z "$IFACE" ]; then
  warn "Could not detect network interface — skipping static IP"
else
  CURRENT_IP=$(ip -4 addr show "$IFACE" 2>/dev/null \
    | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1 || echo "")

  if [ "$CURRENT_IP" = "$STATIC_IP" ]; then
    log "Static IP ${STATIC_IP} already set on $IFACE"
  else
    warn "Setting $IFACE: ${CURRENT_IP:-no IP} → ${STATIC_IP}"

    # Backup any existing netplan configs that reference this interface
    for f in /etc/netplan/*.yaml /etc/netplan/*.yml; do
      [ -f "$f" ] && [ "$f" != "$NETPLAN_CONF" ] && \
        grep -q "$IFACE" "$f" 2>/dev/null && \
        cp "$f" "${f}.bak" && warn "Backed up: $f"
    done

    cat > "$NETPLAN_CONF" << NETEOF
# GAF WiFi Server — Static IP (auto-generated by deploy.sh)
network:
  version: 2
  renderer: networkd
  ethernets:
    ${IFACE}:
      dhcp4: false
      addresses:
        - ${STATIC_IP}/24
      routes:
        - to: default
          via: ${GATEWAY}
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
NETEOF
    chmod 600 "$NETPLAN_CONF"
    netplan generate 2>/dev/null || true
    netplan apply   2>/dev/null || warn "netplan apply had warnings"
    sleep 4

    NEW_IP=$(ip -4 addr show "$IFACE" 2>/dev/null \
      | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1 || echo "")
    if [ "$NEW_IP" = "$STATIC_IP" ]; then
      log "Static IP confirmed: ${STATIC_IP} on $IFACE"
    else
      warn "IP is ${NEW_IP:-unknown} — may need reboot. Continuing anyway..."
    fi
  fi
fi

# ── 3. Clone or update repo ───────────────────────────────────────────────────
if [ -d "$APP_DIR/.git" ]; then
  log "Pulling latest code..."
  git -C "$APP_DIR" fetch origin main
  git -C "$APP_DIR" reset --hard origin/main
else
  log "Cloning repository..."
  git clone "$REPO" "$APP_DIR"
fi

chown -R "$REAL_USER:$REAL_USER" "$APP_DIR"
cd "$APP_DIR"

# ── 4. Directories & permissions ─────────────────────────────────────────────
mkdir -p data logs
chown -R "$REAL_USER:$REAL_USER" data logs
chmod 750 data
log "Directories ready"

# ── 5. .env ───────────────────────────────────────────────────────────────────
if [ ! -f "$APP_DIR/.env" ]; then
  log "Creating .env..."
  cat > "$APP_DIR/.env" << ENVEOF
PORT=3000
BASE_URL=http://${STATIC_IP}
JWT_SECRET=
JWT_EXPIRY=8h
GEMINI_API_KEY=
ENVEOF
  chmod 600 "$APP_DIR/.env"
  chown "$REAL_USER:$REAL_USER" "$APP_DIR/.env"
  log ".env created"
else
  log ".env exists — skipping"
fi

# ── 6. npm install (clean Linux build) ───────────────────────────────────────
log "Installing npm dependencies..."
sudo -u "$REAL_USER" bash -c "
  cd '$APP_DIR'
  rm -rf node_modules
  npm install --no-audit --no-fund 2>&1 | tail -5
"
log "Dependencies installed"

# ── 7. Build frontend ─────────────────────────────────────────────────────────
log "Building frontend..."
sudo -u "$REAL_USER" bash -c "cd '$APP_DIR' && npm run build 2>&1 | tail -5"
[ -d "$APP_DIR/dist" ] || fail "Build failed — dist/ not created"
log "Frontend built"

# ── 8. nginx ──────────────────────────────────────────────────────────────────
log "Configuring nginx..."
cp "$APP_DIR/nginx/gaf-wifi.conf" "$NGINX_CONF"
ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/gaf-wifi
rm -f /etc/nginx/sites-enabled/default
nginx -t 2>&1 || fail "nginx config invalid — check $NGINX_CONF"
systemctl enable nginx --quiet
systemctl restart nginx
log "nginx running on port 80"

# ── 9. Firewall ───────────────────────────────────────────────────────────────
log "Configuring firewall..."
ufw --force reset >/dev/null 2>&1 || true
ufw default deny incoming  >/dev/null 2>&1
ufw default allow outgoing >/dev/null 2>&1
ufw allow 22/tcp   >/dev/null 2>&1   # SSH
ufw allow 80/tcp   >/dev/null 2>&1   # HTTP via nginx
ufw deny  3000/tcp >/dev/null 2>&1   # Block direct Node port
ufw --force enable >/dev/null 2>&1
log "Firewall: SSH(22) + HTTP(80) open | Node(3000) blocked"

# ── 10. PM2 ───────────────────────────────────────────────────────────────────
log "Starting app with PM2..."

# Stop any existing instance cleanly
sudo -u "$REAL_USER" bash -c "
  pm2 stop airforce-app   2>/dev/null || true
  pm2 delete airforce-app 2>/dev/null || true
  pm2 flush               2>/dev/null || true
" || true

sudo -u "$REAL_USER" bash -c "
  cd '$APP_DIR'
  pm2 start ecosystem.config.js --env production
  pm2 save --force
"

# Configure PM2 to start on boot via systemd
env PATH="$PATH:/usr/bin:/usr/local/bin" \
  pm2 startup systemd -u "$REAL_USER" --hp "$REAL_HOME" 2>/dev/null \
  | grep -E "^sudo env" | bash || true

# Enable and start the PM2 systemd service
systemctl enable "pm2-${REAL_USER}" 2>/dev/null || true
log "PM2 auto-start on reboot configured"

# ── 11. PM2 log rotation ──────────────────────────────────────────────────────
sudo -u "$REAL_USER" bash -c "
  pm2 install pm2-logrotate 2>/dev/null || true
  pm2 set pm2-logrotate:max_size 10M  2>/dev/null || true
  pm2 set pm2-logrotate:retain 7      2>/dev/null || true
  pm2 set pm2-logrotate:compress true 2>/dev/null || true
" || true
log "Log rotation configured"

# ── 12. Health check ──────────────────────────────────────────────────────────
log "Waiting for server..."
HTTP="000"
for i in {1..20}; do
  sleep 3
  HTTP=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:3000/api/health 2>/dev/null || echo "000")
  [ "$HTTP" = "200" ] && break
  echo "   Waiting... ($i/20)"
done

if [ "$HTTP" != "200" ]; then
  warn "Node server not responding. Logs:"
  sudo -u "$REAL_USER" pm2 logs airforce-app --lines 50 --nostream 2>/dev/null || true
  fail "Server failed to start — fix errors above and re-run: sudo bash deploy.sh"
fi
log "Node server healthy (HTTP 200)"

# Verify nginx proxy
NGINX_HTTP=$(curl -s -o /dev/null -w "%{http_code}" "http://${STATIC_IP}/api/health" 2>/dev/null || echo "000")
if [ "$NGINX_HTTP" = "200" ]; then
  log "nginx proxy healthy (HTTP 200 via http://${STATIC_IP})"
else
  warn "nginx proxy returned HTTP $NGINX_HTTP — check: sudo nginx -t && sudo systemctl status nginx"
fi

# ── 13. Seed admin ────────────────────────────────────────────────────────────
log "Seeding admin account..."
sudo -u "$REAL_USER" bash -c "
  cd '$APP_DIR'
  NODE_ENV=production ./node_modules/.bin/tsx scripts/reset-admin.ts
"
log "Admin ready"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}   Deployment complete!${NC}"
echo ""
echo "   App URL  : http://${STATIC_IP}"
echo "   Login    : admin@airforce.mil"
echo "   Password : Admin@GAF2026!"
echo ""
echo "   Any device on 192.168.11.x → open http://${STATIC_IP}"
echo ""
echo "   pm2 status                — check app"
echo "   pm2 logs airforce-app     — live logs"
echo "   pm2 restart airforce-app  — restart"
echo "   sudo bash update.sh       — pull & redeploy"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
